#server:
#  port: 9000
#
##定义对象/Map集合
#user:
#  name: Tom
#  age: 20
#  address: beijing
#
##定义数组/List/Set
#hobby:
#  - java
#  - C
#  - game
#  - sport

spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 123456
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tMG1m5zuB3nfGtHYEjp
    accessKeySecret: KaKmKax7wWxshAlVvw6CcOzyugpa6U
    bucketName: snuonuo-web-tlias

